name: rdm_weather_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.20.5
  http: ^1.4.0
  dartz: ^0.10.1
  equatable: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  json_serializable: ^6.6.2
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.4.0
  flutter_gen: ^5.4.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/images/
    - .env 

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true




























